### PR TITLE
Update generated components and reverse accessors for "disabled"

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #2329

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/29)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29#-L4GPN8ZX_gPHFqqGLfv:-L4GPN8ZX_gPHFqqGLfw:bknaifv) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/41347af2d4df279ca8d6f9d787bd737ecb5d05bd/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java#L27)):*
> ```Java
>  */
> class RadioButton<T> extends GeneratedVaadinRadioButton<RadioButton<T>>
>         implements ItemComponent<T>, HasComponents {
> ```

I don't think it does any sense to allow the Java developers to add components to a `RadioButton` - is there any use case for this? If not, the `HasComponents` interface should be removed.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29#-L4GQnehXH3eG4cJ0ssH:-L4GQnehXH3eG4cJ0ssI:bop73it) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/41347af2d4df279ca8d6f9d787bd737ecb5d05bd/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L41)):*
> ```Java
>  */
> public class RadioButtonGroup<T>
>         extends GeneratedVaadinRadioGroup<RadioButtonGroup<T>>
> ```

Now this one makes sense to implement `HasComponents`, since you can add divisors and other stuff between the options.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29)*

**Comment by denis-anisimov** [comment]
@gilberto-torrezan 
Reviewable doesn't work for me , so I answer here:

>Now this one makes sense to implement HasComponents, since you can add divisors and other stuff between the options.

`RadioButtonGroup implements HasItemsAndComponents` the latter interface extends `HasComponents`.
So your comment is resolved.

>I don't think it does any sense to allow the Java developers to add components to a RadioButton - is there any use case for this? If not, the HasComponents interface should be removed.

Developers may be don't need to add components into `RadioButton`  but we do this.
The code from `RadioButtonGroup`:
```
private void updateButton(RadioButton<T> button) {
        button.setDisabled(!getItemEnabledProvider().test(button.getItem()));
        button.removeAll();
        button.add(getItemRenderer().createComponent(button.getItem()));
    }
```
And developers has no access to `RadioButton`  since the class is not public.

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29#-L4GQnehXH3eG4cJ0ssH:-L4K3545Nym4uslIOUdQ:b-3cgzsf) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/41347af2d4df279ca8d6f9d787bd737ecb5d05bd/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L41)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Now this one makes sense to implement `HasComponents`, since you can add divisors and other stuff between the options.
</blockquote></details>

`RadioButtonGroup implements HasItemsAndComponents` the latter interface extends `HasComponents`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29#-L4GPN8ZX_gPHFqqGLfv:-L4K3Q102wXZvW2neiyl:b-wu6666) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/41347af2d4df279ca8d6f9d787bd737ecb5d05bd/src/main/java/com/vaadin/flow/component/radiobutton/RadioButton.java#L27)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I don't think it does any sense to allow the Java developers to add components to a `RadioButton` - is there any use case for this? If not, the `HasComponents` interface should be removed.
</blockquote></details>

Developers may be don't need to add components into `RadioButton`  but we do this.
The code from `RadioButtonGroup`:
```
private void updateButton(RadioButton<T> button) {
        button.setDisabled(!getItemEnabledProvider().test(button.getItem()));
        button.removeAll();
        button.add(getItemRenderer().createComponent(button.getItem()));
    }
```
And developers has no access to `RadioButton`  since the class is not public.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-radio-button-flow/29)*

**Pull request merged**
