### PR TITLE
Use disabled property to mark radio button group as read-only

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #3891

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXgJlQCCECJrT6ixRu:-LAXgJlQCCECJrT6ixRv:b-c09h97) (no related file):*
As a functionality this is fine, but I feel that the graying out of the text is not what one would expect and should not be themed as disabled.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXgJlQCCECJrT6ixRu:-LAXhv98CITionX6IjD0:b-1yunsr) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

As a functionality this is fine, but I feel that the graying out of the text is not what one would expect and should not be themed as disabled.
</blockquote></details>

https://vaadin.slack.com/archives/C3TGRP4HY/p1524214003000305?thread_ts=1524213668.000037&cid=C3TGRP4HY

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46)*

**Comment by gilberto-torrezan** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 153 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXisJMBdTr9fwQ0T-l:-LAXisJMBdTr9fwQ0T-m:b5z5xpq) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/4d9ddd939755c534e38519104757cb2cef2f4677/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L153)):*
> ```Java
>             setDisabled(!enabled);
>         }
>         refreshButtons();
> ```

The whole `refreshButtons` logic seems flawed with the new `HasEnabled` security feature in Flow. Only the `disabled` flag is being set there, but the communication from "enabled" items would still not work in a disabled `RadioButtonGroup`. Or the other way around too - disabled items in an enabled group could still be hacked to communicate with the server.

Not directly related to your patch though.

---

*[src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, line 140 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXjtuP6_L8PI6HJO2n:-LAXjtuP6_L8PI6HJO2o:b-pv6lgi) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/052bade538ac949c9f20bb6b25ab796a64a66487/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java#L140)):*
> ```Java
> 
>         scrollToElement(group);
>         getCommandExecutor().executeScript("window.scrollBy(0,50);");
> ```

Why is this script needed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 153 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXisJMBdTr9fwQ0T-l:-LAXk88b297VwMDA_PtP:brpfl4g) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/4d9ddd939755c534e38519104757cb2cef2f4677/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L153)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The whole `refreshButtons` logic seems flawed with the new `HasEnabled` security feature in Flow. Only the `disabled` flag is being set there, but the communication from "enabled" items would still not work in a disabled `RadioButtonGroup`. Or the other way around too - disabled items in an enabled group could still be hacked to communicate with the server.

Not directly related to your patch though.
</blockquote></details>

`refreshButtons` doesn't relate to this PR at all, sorry.
Please make a ticket if you think there is something wrong.

---

*[src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, line 140 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46#-LAXjtuP6_L8PI6HJO2n:-LAXkLQn527Nb9UQZKmZ:bv6e81b) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/052bade538ac949c9f20bb6b25ab796a64a66487/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java#L140)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Why is this script needed?
</blockquote></details>

I'm experimenting. As I see on the screenshot the scroll doesn't work as expected and nothing os clickable. 
Not sure it helps, let's see.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-radio-button-flow/46)*

**Pull request merged**
