### PR TITLE
Wrong selection of a disabled item should revert.

### PR DESCRIPTION
**Pull request by caalador**
If the user removes the disabled attribute from the
radiobutton the server should not accept the new value.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48#-:-LAqmhgC0QPz0yx9vcLt:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, line 139 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48#-LArXYNw-qCVQavroaZt:-LArXYNw-qCVQavroaZu:bputrd2) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/71ddb83361176c3c3a9b79dca316cc92e6354528/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java#L139)):*
> ```Java
>                 infoLabel.getText());
> 
>         executeScript("arguments[0].removeAttribute(\"disabled\");",
> ```

why not unset the property disabled instead?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48)*

**Comment by caalador** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java, line 139 at r2](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48#-LArXYNw-qCVQavroaZt:-LArZObf6g8hr9aE8uhW:bgswh5c) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/71ddb83361176c3c3a9b79dca316cc92e6354528/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupIT.java#L139)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not unset the property disabled instead?
</blockquote></details>

This feels more like what the user would do. open inspector and just remove 'disabled'.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48#-:-LArhwlD4lATXacYidO2:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/48#-:-LAs9FriDUAKD9hu_Fvd:bnfp4nl)*

**Pull request merged**
