### PR TITLE
Adapt main components to new hasValue API

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 55 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBAIeFr8a1SOgpFQtHH:-LBAIeFr8a1SOgpFQtHI:b-p1r1zc) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L55)):*
> ```Java
>     private boolean isReadOnly;
> 
>     private static final String I18N_PROPERTY = "i18n";
> ```

where is this used?

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBAI2ip13E5Vxt8vM2k:-LBAI2ip13E5Vxt8vM2l:b85vbe7) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L76)):*
> ```Java
>         super(null, null, String.class, RadioButtonGroup::presentationToModel,
>                 RadioButtonGroup::modelToPresentation);
>         getElement().synchronizeProperty(getClientValuePropertyName(),
> ```

I think these line can be removed, since abstract field should take care of synchronising  the value property

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 78 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBALkq1BJ7Y0CuDmkeZ:-LBALkq1BJ7Y0CuDmke_:bqjocr5) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L78)):*
> ```Java
>         getElement().synchronizeProperty(getClientValuePropertyName(),
>                 getClientPropertyChangeEventName());
>         getElement().addPropertyChangeListener(getClientValuePropertyName(),
> ```

`getClientValuePropertyName` is going to be removed in #4003  hence you need wither using 'value' string

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49)*

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 55 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBAIeFr8a1SOgpFQtHH:-LBFLmfW8r9ik9da8YoN:ba3dfob) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L55)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

Removed

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBAI2ip13E5Vxt8vM2k:-LBFLkk_1hyasU_2r0El:b-896fix) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L76)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think these line can be removed, since abstract field should take care of synchronising  the value property
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 78 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBALkq1BJ7Y0CuDmkeZ:-LBFLoeUDVW6ARYKNxgj:brxlxqb) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L78)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`getClientValuePropertyName` is going to be removed in #4003  hence you need wither using 'value' string
</blockquote></details>

where in #4003 are we going to remove it? I couldnt identify it https://github.com/vaadin/flow/pull/4003/files#diff-d0f378d2c47c6e6ac35be27b6f60cf35 what would be the replacement?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49)*

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java, line 78 at r1](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-LBALkq1BJ7Y0CuDmkeZ:-LBKM3cyCUglZKeDXWzn:b-g6e2o9) ([raw file](https://github.com/vaadin/vaadin-radio-button-flow/blob/0e474ee1fdc55302bbe218f9de150868aaae63f7/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java#L78)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

where in #4003 are we going to remove it? I couldnt identify it https://github.com/vaadin/flow/pull/4003/files#diff-d0f378d2c47c6e6ac35be27b6f60cf35 what would be the replacement?
</blockquote></details>

Changed the `getClientValuePropertyName` to `value` string.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49)*

**Comment by manolo** [comment]
Fix CI, otherwise :lgtm: 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-:-LBKMTQ527X0ELYcfDKC:b-bbv4qq)*

**Comment by ZheSun88** [comment]
this needs leif's patch in also.. because of the `ValueChangeEvent`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-radio-button-flow/49#-:-LBKMYAi1ME42zDlccKj:b-buhofj)*

**Pull request merged**
